### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by martian0x80** [martian0x80/ScraperSenpai#2]
Here's the roadmap, we are going to follow:

Endpoint: http://ggsipu.ac.in/ExamResults/ExamResultsmain.htm

- [ ] Get a list of documents.
- [ ] A multi-threaded downloader.
- [ ] File handling.
- [ ] A new naming convention?
- [ ] Tracking downloaded documents.
- [ ] PDF matching.
- [ ] Incremential update/download support.
- [ ] Cron/Daemonize for regular updates.
- [ ] Discord/Telegram webhook support for notifications or updates.
